002 job spec each role
dcorry586/the-it-crowd-ui pull request #12
Opened 2023-11-16 15:25 UTC by dcorry586

2023-11-16 15:43 UTC, TaylorJCrawford commented on services/JobService.ts
> +            // console.log("jobs --> ", response.data);
Needs Removed.

2023-11-20 14:37 UTC, dcorry586 commented on models/JobReset.ts
remove

2023-11-20 14:37 UTC, dcorry586 commented on test/unit/JobServiceTest.ts
> +        const id: number = 1; // Define your id here
remove comment

2023-11-20 14:37 UTC, dcorry586 commented on services/JobService.ts
> +            const response = await axiosInstance.get('/api/jobs/' + id);
remove concatenation - insert template literals

2023-11-20 14:37 UTC, dcorry586 commented on test/unit/JobServiceTest.ts
> +        const id: number = 111; // Define your id here
remove comment

2023-11-21 09:55 UTC, dmkainos requested changes

2023-11-21 09:55 UTC, ghost commented on views/JobTitles.ejs
> +  <nav class="navbar navbar-expand-lg bg-body-tertiary">
The navbar shouldn't be in it

2023-11-21 09:55 UTC, ghost commented on views/JobTitles.ejs
> +  <nav class="navbar navbar-expand-lg bg-body-tertiary">
Actually remove whole file

2023-11-21 10:13 UTC, dmkainos approved these changes

2023-11-21 10:13 UTC, dmkainos approved these changes

2023-11-21 16:07 UTC, glenn-hamilton commented on controllers/JobsController.ts
> +        res.render('pages/JobById', { job, pageTitle: 'Job' });
JobById might not be a good name for this template

2023-11-21 16:07 UTC, glenn-hamilton commented on public/style.css
> +    margin-bottom: 20px;
Could this have unintended consequences elsewhere?

2023-11-22 13:24 UTC, glenn-hamilton approved these changes

2023-11-23 11:32 UTC, merged